import type { AcademicDegree, MemberState, MemberTitle } from "@/lib/types";

export type SelectOption<T extends string> = {
  value: T;
  label: string;
};

export const academicDegreeOptions: Array<SelectOption<AcademicDegree>> = [
  { value: "doctorado", label: "Doctorado" },
  { value: "maestria", label: "Maestría" },
  { value: "licenciatura", label: "Licenciatura" },
  { value: "bachiller", label: "Bachiller" },
  { value: "other", label: "Otro" },
];

export const mexicanStateOptions: Array<SelectOption<MemberState>> = [
  { value: "aguascalientes", label: "Aguascalientes" },
  { value: "baja_california", label: "Baja California" },
  { value: "baja_california_sur", label: "Baja California Sur" },
  { value: "campeche", label: "Campeche" },
  { value: "chiapas", label: "Chiapas" },
  { value: "chihuahua", label: "Chihuahua" },
  { value: "ciudad_de_mexico", label: "Ciudad de México" },
  { value: "coahuila", label: "Coahuila" },
  { value: "colima", label: "Colima" },
  { value: "durango", label: "Durango" },
  { value: "estado_de_mexico", label: "Estado de México" },
  { value: "guanajuato", label: "Guanajuato" },
  { value: "guerrero", label: "Guerrero" },
  { value: "hidalgo", label: "Hidalgo" },
  { value: "jalisco", label: "Jalisco" },
  { value: "michoacan", label: "Michoacán" },
  { value: "morelos", label: "Morelos" },
  { value: "nayarit", label: "Nayarit" },
  { value: "nuevo_leon", label: "Nuevo León" },
  { value: "oaxaca", label: "Oaxaca" },
  { value: "puebla", label: "Puebla" },
  { value: "queretaro", label: "Querétaro" },
  { value: "quintana_roo", label: "Quintana Roo" },
  { value: "san_luis_potosi", label: "San Luis Potosí" },
  { value: "sinaloa", label: "Sinaloa" },
  { value: "sonora", label: "Sonora" },
  { value: "tabasco", label: "Tabasco" },
  { value: "tamaulipas", label: "Tamaulipas" },
  { value: "tlaxcala", label: "Tlaxcala" },
  { value: "veracruz", label: "Veracruz" },
  { value: "yucatan", label: "Yucatán" },
  { value: "zacatecas", label: "Zacatecas" },
  { value: "other", label: "Otro" },
];

export const memberTitleOptions: Array<SelectOption<MemberTitle>> = [
  { value: "dr", label: "Dr." },
  { value: "dra", label: "Dra." },
  { value: "mtro", label: "Mtro." },
  { value: "mtra", label: "Mtra." },
  { value: "ing", label: "Ing." },
  { value: "lic", label: "Lic." },
  { value: "sr", label: "Sr." },
  { value: "sra", label: "Sra." },
  { value: "srta", label: "Srta." },
  { value: "other", label: "Otro" },
];

export const mexicanInstitutionOptions: Array<SelectOption<string>> = [
  { value: "unam", label: "Universidad Nacional Autónoma de México" },
  { value: "ipn", label: "Instituto Politécnico Nacional" },
  { value: "uam", label: "Universidad Autónoma Metropolitana" },
  { value: "chapingo", label: "Universidad Autónoma Chapingo" },
  { value: "colmex", label: "El Colegio de México" },
  { value: "cide", label: "Centro de Investigación y Docencia Económicas" },
  { value: "cinvestav", label: "CINVESTAV" },
  { value: "tec_de_monterrey", label: "Tecnológico de Monterrey" },
  { value: "iteso", label: "ITESO" },
  { value: "ibero", label: "Universidad Iberoamericana" },
  { value: "anahuac", label: "Universidad Anáhuac" },
  { value: "la_salle", label: "Universidad La Salle" },
  { value: "panamericana", label: "Universidad Panamericana" },
  { value: "udlap", label: "Universidad de las Américas Puebla" },
  { value: "uady", label: "Universidad Autónoma de Yucatán" },
  { value: "uanl", label: "Universidad Autónoma de Nuevo León" },
  { value: "udeg", label: "Universidad de Guadalajara" },
  { value: "ugto", label: "Universidad de Guanajuato" },
  { value: "uaq", label: "Universidad Autónoma de Querétaro" },
  { value: "uaslp", label: "Universidad Autónoma de San Luis Potosí" },
  { value: "uv", label: "Universidad Veracruzana" },
  { value: "buap", label: "Benemérita Universidad Autónoma de Puebla" },
  { value: "uaemex", label: "Universidad Autónoma del Estado de México" },
  { value: "uaem_morelos", label: "Universidad Autónoma del Estado de Morelos" },
  { value: "uach_chihuahua", label: "Universidad Autónoma de Chihuahua" },
  { value: "uach_chapingo", label: "Universidad Autónoma Chapingo" },
  { value: "uabc", label: "Universidad Autónoma de Baja California" },
  { value: "uabcs", label: "Universidad Autónoma de Baja California Sur" },
  { value: "uacam", label: "Universidad Autónoma de Campeche" },
  { value: "unach", label: "Universidad Autónoma de Chiapas" },
  { value: "uadec", label: "Universidad Autónoma de Coahuila" },
  { value: "ucol", label: "Universidad de Colima" },
  { value: "ujed", label: "Universidad Juárez del Estado de Durango" },
  { value: "uagro", label: "Universidad Autónoma de Guerrero" },
  { value: "uaeh", label: "Universidad Autónoma del Estado de Hidalgo" },
  { value: "umsnh", label: "Universidad Michoacana de San Nicolás de Hidalgo" },
  { value: "uan", label: "Universidad Autónoma de Nayarit" },
  { value: "uabjo", label: "Universidad Autónoma Benito Juárez de Oaxaca" },
  { value: "uqroo", label: "Universidad Autónoma del Estado de Quintana Roo" },
  { value: "uas", label: "Universidad Autónoma de Sinaloa" },
  { value: "unison", label: "Universidad de Sonora" },
  { value: "ujat", label: "Universidad Juárez Autónoma de Tabasco" },
  { value: "uat", label: "Universidad Autónoma de Tamaulipas" },
  { value: "uatx", label: "Universidad Autónoma de Tlaxcala" },
  { value: "uaz", label: "Universidad Autónoma de Zacatecas" },
  { value: "itmerida", label: "Instituto Tecnológico de Mérida" },
  { value: "tecnm", label: "Tecnológico Nacional de México" },
  { value: "universidad_pedagogica_nacional", label: "Universidad Pedagógica Nacional" },
  { value: "universidad_autonoma_agraria_antonio_narro", label: "Universidad Autónoma Agraria Antonio Narro" },
  { value: "universidad_del_pedregal", label: "Universidad del Pedregal" },
  { value: "universidad_insurgentes", label: "Universidad Insurgentes" },
  { value: "universidad_del_valle_de_mexico", label: "Universidad del Valle de México" },
  { value: "universidad_tecmilenio", label: "Universidad Tecmilenio" },
  { value: "universidad_del_valle_de_atemajac", label: "Universidad del Valle de Atemajac" },
  { value: "universidad_marista", label: "Universidad Marista" },
  { value: "universidad_mesoamericana", label: "Universidad Mesoamericana" },
  { value: "universidad_regiomontana", label: "Universidad Regiomontana" },
  { value: "universidad_de_monterrey", label: "Universidad de Monterrey" },
  { value: "universidad_del_claustro_de_sor_juana", label: "Universidad del Claustro de Sor Juana" },
  { value: "universidad_autonoma_de_occidente", label: "Universidad Autónoma de Occidente" },
  { value: "other", label: "Otra" },
];
