import type { AcademicDegree, MemberState, MemberTitle } from "@/lib/types";

export type SelectOption<T extends string> = {
  value: T;
  label: string;
};

export const academicDegreeOptions: Array<SelectOption<AcademicDegree>> = [
  { value: "doctorado", label: "Doctorado" },
  { value: "maestria", label: "Maestria" },
  { value: "licenciatura", label: "Licenciatura" },
  { value: "bachiller", label: "Bachiller" },
  { value: "other", label: "Otro" },
];

export const mexicanStateOptions: Array<SelectOption<MemberState>> = [
  { value: "aguascalientes", label: "Aguascalientes" },
  { value: "baja_california", label: "Baja California" },
  { value: "baja_california_sur", label: "Baja California Sur" },
  { value: "campeche", label: "Campeche" },
  { value: "chiapas", label: "Chiapas" },
  { value: "chihuahua", label: "Chihuahua" },
  { value: "ciudad_de_mexico", label: "Ciudad de Mexico" },
  { value: "coahuila", label: "Coahuila" },
  { value: "colima", label: "Colima" },
  { value: "durango", label: "Durango" },
  { value: "estado_de_mexico", label: "Estado de Mexico" },
  { value: "guanajuato", label: "Guanajuato" },
  { value: "guerrero", label: "Guerrero" },
  { value: "hidalgo", label: "Hidalgo" },
  { value: "jalisco", label: "Jalisco" },
  { value: "michoacan", label: "Michoacan" },
  { value: "morelos", label: "Morelos" },
  { value: "nayarit", label: "Nayarit" },
  { value: "nuevo_leon", label: "Nuevo Leon" },
  { value: "oaxaca", label: "Oaxaca" },
  { value: "puebla", label: "Puebla" },
  { value: "queretaro", label: "Queretaro" },
  { value: "quintana_roo", label: "Quintana Roo" },
  { value: "san_luis_potosi", label: "San Luis Potosi" },
  { value: "sinaloa", label: "Sinaloa" },
  { value: "sonora", label: "Sonora" },
  { value: "tabasco", label: "Tabasco" },
  { value: "tamaulipas", label: "Tamaulipas" },
  { value: "tlaxcala", label: "Tlaxcala" },
  { value: "veracruz", label: "Veracruz" },
  { value: "yucatan", label: "Yucatan" },
  { value: "zacatecas", label: "Zacatecas" },
  { value: "other", label: "Otro" },
];

export const memberTitleOptions: Array<SelectOption<MemberTitle>> = [
  { value: "dr", label: "Dr." },
  { value: "dra", label: "Dra." },
  { value: "mtro", label: "Mtro." },
  { value: "mtra", label: "Mtra." },
  { value: "ing", label: "Ing." },
  { value: "lic", label: "Lic." },
  { value: "sr", label: "Sr." },
  { value: "sra", label: "Sra." },
  { value: "srta", label: "Srta." },
  { value: "other", label: "Otro" },
];

export const mexicanInstitutionOptions: Array<SelectOption<string>> = [
  { value: "unam", label: "Universidad Nacional Autonoma de Mexico" },
  { value: "ipn", label: "Instituto Politecnico Nacional" },
  { value: "uam", label: "Universidad Autonoma Metropolitana" },
  { value: "chapingo", label: "Universidad Autonoma Chapingo" },
  { value: "colmex", label: "El Colegio de Mexico" },
  { value: "cide", label: "Centro de Investigacion y Docencia Economicas" },
  { value: "cinvestav", label: "CINVESTAV" },
  { value: "tec_de_monterrey", label: "Tecnologico de Monterrey" },
  { value: "iteso", label: "ITESO" },
  { value: "ibero", label: "Universidad Iberoamericana" },
  { value: "anahuac", label: "Universidad Anahuac" },
  { value: "la_salle", label: "Universidad La Salle" },
  { value: "panamericana", label: "Universidad Panamericana" },
  { value: "udlap", label: "Universidad de las Americas Puebla" },
  { value: "uady", label: "Universidad Autonoma de Yucatan" },
  { value: "uanl", label: "Universidad Autonoma de Nuevo Leon" },
  { value: "udeg", label: "Universidad de Guadalajara" },
  { value: "ugto", label: "Universidad de Guanajuato" },
  { value: "uaq", label: "Universidad Autonoma de Queretaro" },
  { value: "uaslp", label: "Universidad Autonoma de San Luis Potosi" },
  { value: "uv", label: "Universidad Veracruzana" },
  { value: "buap", label: "Benemerita Universidad Autonoma de Puebla" },
  { value: "uaemex", label: "Universidad Autonoma del Estado de Mexico" },
  { value: "uaem_morelos", label: "Universidad Autonoma del Estado de Morelos" },
  { value: "uach_chihuahua", label: "Universidad Autonoma de Chihuahua" },
  { value: "uach_chapingo", label: "Universidad Autonoma Chapingo" },
  { value: "uabc", label: "Universidad Autonoma de Baja California" },
  { value: "uabcs", label: "Universidad Autonoma de Baja California Sur" },
  { value: "uacam", label: "Universidad Autonoma de Campeche" },
  { value: "unach", label: "Universidad Autonoma de Chiapas" },
  { value: "uadec", label: "Universidad Autonoma de Coahuila" },
  { value: "ucol", label: "Universidad de Colima" },
  { value: "ujed", label: "Universidad Juarez del Estado de Durango" },
  { value: "uagro", label: "Universidad Autonoma de Guerrero" },
  { value: "uaeh", label: "Universidad Autonoma del Estado de Hidalgo" },
  { value: "umsnh", label: "Universidad Michoacana de San Nicolas de Hidalgo" },
  { value: "uan", label: "Universidad Autonoma de Nayarit" },
  { value: "uabjo", label: "Universidad Autonoma Benito Juarez de Oaxaca" },
  { value: "uqroo", label: "Universidad Autonoma del Estado de Quintana Roo" },
  { value: "uas", label: "Universidad Autonoma de Sinaloa" },
  { value: "unison", label: "Universidad de Sonora" },
  { value: "ujat", label: "Universidad Juarez Autonoma de Tabasco" },
  { value: "uat", label: "Universidad Autonoma de Tamaulipas" },
  { value: "uatx", label: "Universidad Autonoma de Tlaxcala" },
  { value: "uaz", label: "Universidad Autonoma de Zacatecas" },
  { value: "itmerida", label: "Instituto Tecnologico de Merida" },
  { value: "tecnm", label: "Tecnologico Nacional de Mexico" },
  { value: "universidad_pedagogica_nacional", label: "Universidad Pedagogica Nacional" },
  { value: "universidad_autonoma_agraria_antonio_narro", label: "Universidad Autonoma Agraria Antonio Narro" },
  { value: "universidad_del_pedregal", label: "Universidad del Pedregal" },
  { value: "universidad_insurgentes", label: "Universidad Insurgentes" },
  { value: "universidad_del_valle_de_mexico", label: "Universidad del Valle de Mexico" },
  { value: "universidad_tecmilenio", label: "Universidad Tecmilenio" },
  { value: "universidad_del_valle_de_atemajac", label: "Universidad del Valle de Atemajac" },
  { value: "universidad_marista", label: "Universidad Marista" },
  { value: "universidad_mesoamericana", label: "Universidad Mesoamericana" },
  { value: "universidad_regiomontana", label: "Universidad Regiomontana" },
  { value: "universidad_de_monterrey", label: "Universidad de Monterrey" },
  { value: "universidad_del_claustro_de_sor_juana", label: "Universidad del Claustro de Sor Juana" },
  { value: "universidad_autonoma_de_occidente", label: "Universidad Autonoma de Occidente" },
  { value: "other", label: "Otra" },
];
